"""create baskets table

Revision ID: 67d136e49ef1
Revises: 49db3b455fa7
Create Date: 2026-08-09 22:34:06.786785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d136e49ef1'
down_revision: Union[str, Sequence[str], None] = '49db3b455fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('transport_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('housing_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('healthcare_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('clothing_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('other_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baskets')
    # ### end Alembic commands ###
