"""replace lkr_usd with exchange_rates multi-currency

Revision ID: 913bc8c2dd67
Revises: fff89817f02f
Create Date: 2026-06-03 12:04:18.473653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '913bc8c2dd67'
down_revision: Union[str, Sequence[str], None] = 'fff89817f02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'currency', name='uq_exchange_date_currency')
    )
    op.create_index('idx_exchange_rates_currency', 'exchange_rates', ['currency'], unique=False)
    op.create_index('idx_exchange_rates_date', 'exchange_rates', ['date'], unique=False)
    op.drop_table('lkr_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lkr_usd',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lkr_usd_pkey')),
    sa.UniqueConstraint('date', name=op.f('lkr_usd_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('idx_exchange_rates_date', table_name='exchange_rates')
    op.drop_index('idx_exchange_rates_currency', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
