"""initial schema

Revision ID: fff89817f02f
Revises: 
Create Date: 2026-06-01 22:19:02.561595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff89817f02f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cbsl_rates_date'), table_name='cbsl_rates')
    op.drop_index(op.f('idx_foreign_flow_date'), table_name='foreign_flow')
    op.drop_constraint(op.f('sector_indices_date_sector_key'), 'sector_indices', type_='unique')
    op.create_unique_constraint('uq_sector_date', 'sector_indices', ['date', 'sector'])
    op.drop_constraint(op.f('stock_prices_date_symbol_key'), 'stock_prices', type_='unique')
    op.create_unique_constraint('uq_stock_date_symbol', 'stock_prices', ['date', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stock_date_symbol', 'stock_prices', type_='unique')
    op.create_unique_constraint(op.f('stock_prices_date_symbol_key'), 'stock_prices', ['date', 'symbol'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_sector_date', 'sector_indices', type_='unique')
    op.create_unique_constraint(op.f('sector_indices_date_sector_key'), 'sector_indices', ['date', 'sector'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_foreign_flow_date'), 'foreign_flow', ['date'], unique=False)
    op.create_index(op.f('idx_cbsl_rates_date'), 'cbsl_rates', ['date'], unique=False)
    # ### end Alembic commands ###
